# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Final_NHS_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Final_NHS_App
	pod 'Firebase/Core'
	pod 'Firebase/Analytics'
	pod 'Firebase/Database'
	pod 'IQKeyboardManagerSwift'
end
